export const EngData = {
  "1": "Why attend?",
  "2": "Program",
  "3": "People",
  "4": "Tickets",
  "5": "About",
  "6": "Inviting all",
  "7": "eSports",
  "8": "fans!",
  "9": "Buy a ticket",
  "10": "Become a partner",
  "11": "Meet us in Kultuurikatel on 30 & 31 August",
  "12": "",
  "13": "DIVE INTO THE WORLD OF",
  "14": "TALLINN GAMING SUMMIT",
  "15": "Compete, Enjoy, Learn, Network, Listen",
  "16": "Welcome to the eSports festival, that brings together the entire eSports community. 2 days of playing, competing, exciting discussions, performances by professionals, presentations of new games, meetings with idols and many surprises!",
  "17": "EVENT PROGRAM",
  "18": "Tuesday 30.08",
  "19": "View All",
  "20": "Wednesday 31.08",
  "21": "Nordic Esports Summit",
  "22": "Rocket League show-match",
  "23": "Dota 2 Estonian Championships final",
  "24": "Launch of Estonian Esports Business League",
  "25": "Official Afterparty",
  "26": "Estonian athletes esports battle",
  "27": "Sim-racing showcase",
  "28": "Family Esports showdown",
  "29": "CS:GO Pro teams showmatch",
  "30": "Gaming Summit Quest final",
  "31": "meet the ",
  "32": "speakers",
  "33": "IESF President",
  "34": "Vlad Marinescu",
  "35": "IESF GENERAL SECRETARY",
  "36": "Boban Totovski",
  "37": "MORE SPEAKERS ANNOUNCED SOON",
  "38": "Tickets",
  "39": "All ticket types are available as day tickets.",
  "40": "Children",
  "41": "Regular",
  "42": "Fan",
  "43": "Buy now",
  "44": "EMOTIONS",
  "45": "Event",
  "46": "Highlights",
  "47": "DOTA 2",
  "48": "Estonian champioships FINAL",
  "49": "",
  "50": "",
  "51": "Tallinn Gaming Summit 2022 will be host to the live final of Dota 2 Estonian Championships, where the winning team will qualify for European Championships in Dota 2, taking place in Tirana, Albania.",
  "52": "Participate",
  "53": "YOUR",
  "54": "Game presentation",
  "55": "HISTORY",
  "56": "We are offering a platform for game developers to  share their creations directly with the esports sector, whether you are an indie developer or a triple A studio executive.",
  "57": "This is Tallinn",
  "58": "KULTUURI",
  "59": "KATEL",
  "60": "The Creative Hub is one of the most unique creative and event spaces in Northern Europe.",
  "61": " The Creative Hub is located in the heart of Tallinn. It’s easy to get here by any means of transport and hotels are within walking distance.",
  "62": "The building of the Creative Hub was completed as Tallinn City Central Power Station in 1913. After a long hiatus, the stunning industrial complex was re-opened in 2015 as a renovated universal creative and event centre.",
  "63": "Come enjoy the",
  "64": "event",
  "65": "with us",
  "66": "Want to present your game, showcase your product or want to cooperate with us",
  "67": "Get in touch",
  "68": "WE VALUE YOUR PRIVACY",
  "69": "The information you provide is used solely for the use of the virtual private network. We will not sell your information to any other party.",
  "70": "CUSTOMER SUPPORT",
  "71": "Have any more question? Write us at info@tallinngamingsummit.com",
  "72": "FIND US ON SOCIAL MEDIA",
  "73": "Copyright ® 2022 All rights reserved",
  "74": "This is your day",
  "75": "close",
  "76": "Philip Wride",
  "77": "Cheesecake Digital",
  "78": "News",
  "79": "Home",
  "80": "Read More",
  "81": "Share",
  "82": "Latest Blog Post",
  "83": "Read our latest blog post and learn more.",
};

export const RusData = {
  "1": "Why attend?",
  "2": "Program",
  "3": "People",
  "4": "Tickets",
  "5": "About",
  "6": "Inviting all",
  "7": "eSports",
  "8": "fans!",
  "9": "Buy a ticket",
  "10": "Become a partner",
  "11": "Meet us in Kultuurikatel on 30 & 31 August",
  "12": "ddddd",
  "13": "DIVE INTO THE WORLD OF",
  "14": "TALLINN GAMING SUMMIT",
  "15": "Compete, Enjoy, Learn, Network, Listen",
  "16": "Welcome to the eSports festival, that brings together the entire eSports community. 2 days of playing, competing, exciting discussions, performances by professionals, presentations of new games, meetings with idols and many surprises!",
  "17": "EVENT PROGRAM",
  "18": "Tuesday 30.08",
  "19": "View All",
  "20": "Wednesday 31.08",
  "21": "Nordic Esports Summit",
  "22": "Rocket League show-match",
  "23": "Dota 2 Estonian Championships final",
  "24": "Launch of Estonian Esports Business League",
  "25": "Official Afterparty",
  "26": "Estonian athletes esports battle",
  "27": "Sim-racing showcase",
  "28": "Family Esports showdown",
  "29": "CS:GO Pro teams showmatch",
  "30": "Gaming Summit Quest final",
  "31": "meet the ",
  "32": "speakers",
  "33": "IESF President",
  "34": "Vlad Marinescu",
  "35": "IESF GENERAL SECRETARY",
  "36": "Boban Totovski",
  "37": "MORE SPEAKERS ANNOUNCED SOON",
  "38": "Tickets",
  "39": "All ticket types are available as day tickets.",
  "40": "Children",
  "41": "Regular",
  "42": "Fan",
  "43": "Buy now",
  "44": "EMOTIONS",
  "45": "Event",
  "46": "Highlights",
  "47": "DOTA 2",
  "48": "Estonian champioships FINAL",
  "49": "",
  "50": "",
  "51": "Tallinn Gaming Summit 2022 will be host to the live final of Dota 2 Estonian Championships, where the winning team will qualify for European Championships in Dota 2, taking place in Tirana, Albania.",
  "52": "Participate",
  "53": "YOUR",
  "54": "Game presentation",
  "55": "HISTORY",
  "56": "We are offering a platform for game developers to  share their creations directly with the esports sector, whether you are an indie developer or a triple A studio executive.",
  "57": "This is Tallinn",
  "58": "KULTUURI",
  "59": "KATEL",
  "60": "The Creative Hub is one of the most unique creative and event spaces in Northern Europe.",
  "61": " The Creative Hub is located in the heart of Tallinn. It’s easy to get here by any means of transport and hotels are within walking distance.",
  "62": "The building of the Creative Hub was completed as Tallinn City Central Power Station in 1913. After a long hiatus, the stunning industrial complex was re-opened in 2015 as a renovated universal creative and event centre.",
  "63": "Come enjoy the",
  "64": "event",
  "65": "with us",
  "66": "Want to present your game, showcase your product or want to cooperate with us",
  "67": "Get in touch",
  "68": "WE VALUE YOUR PRIVACY",
  "69": "The information you provide is used solely for the use of the virtual private network. We will not sell your information to any other party.",
  "70": "CUSTOMER SUPPORT",
  "71": "Have any more question? Write us at info@tallinngamingsummit.com",
  "72": "FIND US ON SOCIAL MEDIA",
  "73": "Copyright ® 2022 All rights reserved",
  "74": "This is your day",
  "75": "close",
  "76": "Philip Wride",
  "77": "Cheesecake Digital",
  "78": "News",
  "79": "Home",
  "80": "Read More",
  "81": "Share",
  "82": "Latest Blog Post",
  "83": "Read our latest blog post and learn more.",
};

export const EstData = {
  "1": "Miks osaleda?",
  "2": "Programm",
  "3": "inimesed",
  "4": "piletid",
  "5": "Meist",
  "6": "Kutsume kõiki",
  "7": "espordi ",
  "8": "fänne!",
  "9": "Osta pilet",
  "10": "Hakka partneriks",
  "11": "Kohtume Kultuurikatlas 30. ja 31. augustil",
  "12": "",
  "13": "Tule sukeldu",
  "14": "tallinn gaming summiti maailma!",
  "15": "Võistle, Naudi, Õpi, Suhtle, Kuula",
  "16": "Toome Teieni e-spordi festivali, mis toob kokku kogu e-spordi kogukonna. 2 päeva mängimist, võistlemist, põnevaid arutelusid, professionaalide esinemisi, uute mängude esitlusi, kohtumised iidolitega ja palju üllatusi!",
  "17": "ÜRITUSE PROGRAMM",
  "18": "TEISIPÄEV 30.08",
  "19": "Kogu kava",
  "20": "KOLMAPÄEV 31.08",
  "21": "Nordic Esports Summit",
  "22": "Rocket League näidisvõistlus",
  "23": "Dota 2 Eesti meistrivõistluste finaal",
  "24": "Eesti E-spordi Äriliiga lansseerimine",
  "25": "Ametlik pidu",
  "26": "Eesti sportlaste e-spordi lahing",
  "27": "Sim-racing näidisvõistlus",
  "28": "E-spordi võistlus kogu perele",
  "29": "CS:GO Pro tiimide show-match ",
  "30": "Gaming Summit Quest finaal",
  "31": "TUTVU",
  "32": "esinejatega",
  "33": "IESF President",
  "34": "Vlad Marinescu",
  "35": "IESF PEASEKRETÄR",
  "36": "Boban Totovski",
  "37": "Varsti kuulutame välja...",
  "38": "PILETID",
  "39": "Kõik piletitüübid on saadaval päevapiletitena.",
  "40": "LASTEPILET",
  "41": "TAVAPILET",
  "42": " FÄNNIPILET",
  "43": "Osta",
  "44": "EMotsioon",
  "45": "Ürituse ",
  "46": "Tipphetked",
  "47": "DOTA 2 ",
  "48": "Eesti meistrivõistluste FINaAL",
  "49": "",
  "50": "",
  "51": "Tallinn Gaming Summit 2022 raames toimub Dota 2 Eesti meistrivõistluste finaal, mille võitnud tiim saab pääsme Dota 2 Euroopa meistrivõistlustele Tiranas, Albaanias ",
  "52": "",
  "53": "TEIE ",
  "54": "Mängu esitlus",
  "55": "AJALUGU",
  "56": "Me pakume mängutootjatele platvormi, kus on võimalik enda mängu esitleda otse kogukonnale, ole sa indie mängu arendaja või suure stuudio juht.         ",
  "57": "TALLINNA LINN",
  "58": "KULTUURI",
  "59": "KATEL",
  "60": "Tallinna Kultuurikatel on Põhja-Euroopa üks erilisemaid üritus- ja loomekeskusi.",
  "61": "Kultuurikatel asub Tallinna südalinnas. Siia on väga mugav tulla mistahes transpordivahendiga ja hotellid on jalutuskäigu kaugusel.",
  "62": "Kultuurikatla hoone valmis 1913. aastal kui esimene Tallinna Linna Elektri Keskjaam. Peale pikka pausi avas industriaalselt lummav hoone uuesti uksed 2015. aastal, nüüd juba renoveeritud mitmekülgse üritus- ja loomekeskusena.",
  "63": "Tule  ja  avasta",
  "64": "e-spordi",
  "65": "maailma",
  "66": "Kas soovid esitleda oma mängu või toodet?",
  "67": "Võta ühendust",
  "68": "ME HINDAME TEIE PRIVAATSUST",
  "69": "Teie esitatud teavet kasutatakse ainult virtuaalse privaatvõrgu kasutamiseks. Me ei müü teie andmeid kolmandatele osapooltele.",
  "70": "KLIENDITUGI",
  "71": "Tekkis veel küsimusi? Kirjuta meile!info@tallinngamingsummit.com",
  "72": "LEIA MEID SOTSIAALMEEDIAST",
  "73": "Copyright ® 2022 Kõik õigused kaitstud",
  "74": "võistle",
  "75": "sulge",
  "76": "Philip Wride",
  "77": "Cheesecake Digital",
  "78": "Uudised",
  "79": "Kodu",
  "80": "Loe rohkem",
  "81": "Jaga",
  "82": "Viimane ajaveebi postitus",
  "83": "Lugege meie viimast ajaveebi postitust ja lugege lisateavet.",
};
